sort:
  enabled: true
  by: required
content: |-
  ## Terraform module - addons
  
  This module installs Kubernetes tools which are prerequisites for Armada.

  {{ .Requirements }}
  
  {{ .Modules }}
  
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
  
  ## Example

  ```hcl
  {{ include "../../examples/addons/main.tf" }}
  ```

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

