prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

prometheusOperator:
  namespaces:
   releaseNamespace: true
   additional:
   - gr-system
   - armada
