{
 "title": "Armada - Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Queued jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "armada:queue:size", "legendFormat": "{{ queueName }}" }
   ]
  },
  {
   "title": "Queue priority",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "armada:queue:priority", "legendFormat": "{{ queueName }}" }
   ]
  },
  {
   "title": "Queue share",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(armada:queue:size > bool 1) *  (100 / armada:queue:priority)  / scalar(sum((armada:queue:size > bool 1) * (1 / armada:queue:priority)))",
     "legendFormat": "{{ queueName }}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$cluster - Running pods cpu request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "armada:monitoring:armada_pod_cpu_request:sum{phase=\"Running\"}",
     "legendFormat": "{{ label_armada_queue_id }}"
    },
    {
     "expr": " node:worker_node_allocatable_cpu_cores:sum",
     "legendFormat": "Available CPU"
    },
    {
     "expr": "container:worker_node_cpu_usage_seconds_total:sum",
     "legendFormat": "Used CPU"
    }
   ]
  },
  {
   "title": "$cluster - Running pods cpu request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "armada:monitoring:armada_pod_cpu_request:sum{phase=\"Running\"}",
     "legendFormat": "{{ label_armada_queue_id }}"
    },
    {
     "expr": " node:worker_node_allocatable_cpu_cores:sum",
     "legendFormat": "Available CPU"
    },
    {
     "expr": "container:worker_node_cpu_usage_seconds_total:sum",
     "legendFormat": "Used CPU"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$cluster - Running pods memory request by queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "armada:monitoring:armada_pod_memory_request:sum{phase=\"Running\"}",
     "legendFormat": "{{ label_armada_queue_id }}"
    },
    {
     "expr": " node:worker_node_allocatable_memory_bytes:sum",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "container:worker_node_memory_usage_bytes:sum",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "$cluster - Running pods memory request by queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "armada:monitoring:armada_pod_memory_request:sum{phase=\"Running\"}",
     "legendFormat": "{{ label_armada_queue_id }}"
    },
    {
     "expr": " node:worker_node_allocatable_memory_bytes:sum",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "container:worker_node_memory_usage_bytes:sum",
     "legendFormat": "Memory used"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$cluster - Pods by phase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namespace:pods_per_phase:sum{namespace=\"default\"} ",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "$cluster - Pods by phase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namespace:pods_per_phase:sum{namespace=\"default\"} ",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}