sort:
  enabled: true
  by: required
content: |-
  ## Terraform module - k8s
  
  This module creates a Kubernetes cluster in an AWS VPC.
  
  This module is recommended to be used with [network](https://github.com/dejanzele/armada-infra/tree/main/terraform/modules/network)
  Terraform module.

  {{ .Requirements }}
  
  {{ .Modules }}
  
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
  
  ## Example

  ```hcl
  {{ include "../../examples/k8s/main.tf" }}
  ```

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

